### Add Contact
POST http://localhost:3214/contacts
Content-Type: application/json

{
    "name": "Samantha",
    "last_name":"Doe",
    "email":"sam_doe@gmail.com",
    "phone_number":600000021
}
### Add Second Contact
POST http://localhost:3214/contacts
Content-Type: application/json

{
    "name": "Jhon",
    "last_name":"Doe",
    "email":"jon_doe@gmail.com",
    "phone_number":600000000
}
### Delete Contact
DELETE http://localhost:3214/contacts/1

### Update contact Info

PUT http://localhost:3214/contacts/2
Content-Type: application/json

{
    "name": "Jhon",
    "last_name":"Doe edited",
    "email":"jon_doe@gmail.com",
    "phone_number":600000000
}

### Mark Favorite Conctact

PATCH http://localhost:3214/contacts/2/favorites

### Recover Contact by ID

PATCH http://localhost:3214/contacts/1/recover

### Show Contact List
GET http://localhost:3214/contacts

### Show Contact by ID

GET http://localhost:3214/contacts/1
